export type Country = {
  id: string;
  name: string;
  aliases: string[];
};

export const COUNTRIES: Country[] = [
  { id: "IDN", name: "Indonesia", aliases: ["Republic of Indonesia"] },
  { id: "MYS", name: "Malaysia", aliases: [] },
  { id: "CHL", name: "Chile", aliases: ["Republic of Chile"] },
  { id: "BOL", name: "Bolivia", aliases: ["Plurinational State of Bolivia"] },
  { id: "PER", name: "Peru", aliases: ["Republic of Peru"] },
  { id: "ARG", name: "Argentina", aliases: ["Argentine Republic"] },
  { id: "GBR", name: "United Kingdom", aliases: ["Britain", "Great Britain", "UK", "United Kingdom of Great Britain and Northern Ireland"] },
  { id: "CYP", name: "Cyprus", aliases: ["Republic of Cyprus"] },
  { id: "IND", name: "India", aliases: ["Republic of India"] },
  { id: "CHN", name: "China", aliases: ["People's Republic of China", "PRC"] },
  { id: "ISR", name: "Israel", aliases: ["State of Israel"] },
  { id: "LBN", name: "Lebanon", aliases: ["Lebanese Republic"] },
  { id: "ETH", name: "Ethiopia", aliases: ["Federal Democratic Republic of Ethiopia"] },
  { id: "SDS", name: "South Sudan", aliases: ["Republic of South Sudan"] },
  { id: "SOM", name: "Somalia", aliases: ["Federal Republic of Somalia"] },
  { id: "KEN", name: "Kenya", aliases: ["Republic of Kenya"] },
  { id: "MWI", name: "Malawi", aliases: ["Republic of Malawi"] },
  { id: "TZA", name: "Tanzania", aliases: ["United Republic of Tanzania"] },
  { id: "SYR", name: "Syria", aliases: ["Syrian Arab Republic"] },
  { id: "FRA", name: "France", aliases: ["French Republic"] },
  { id: "SUR", name: "Suriname", aliases: ["Republic of Suriname"] },
  { id: "GUY", name: "Guyana", aliases: ["Co-operative Republic of Guyana"] },
  { id: "KOR", name: "South Korea", aliases: ["Korea", "Republic of Korea", "ROK"] },
  { id: "PRK", name: "North Korea", aliases: ["Democratic People's Republic of Korea", "DPR Korea", "DPRK"] },
  { id: "MAR", name: "Morocco", aliases: ["Kingdom of Morocco"] },
  { id: "CRI", name: "Costa Rica", aliases: ["Republic of Costa Rica"] },
  { id: "NIC", name: "Nicaragua", aliases: ["Republic of Nicaragua"] },
  { id: "COG", name: "Congo", aliases: ["Congo Republic", "Congo-Brazzaville", "Rep Congo", "Republic of the Congo"] },
  { id: "COD", name: "DR Congo", aliases: ["Congo-Kinshasa", "Dem. Rep. Congo", "Democratic Republic of Congo", "Democratic Republic of the Congo", "DRC"] },
  { id: "BTN", name: "Bhutan", aliases: ["Kingdom of Bhutan"] },
  { id: "UKR", name: "Ukraine", aliases: [] },
  { id: "PSX", name: "Palestine", aliases: ["State of Palestine", "West Bank and Gaza"] },
  { id: "BLR", name: "Belarus", aliases: ["Republic of Belarus"] },
  { id: "NAM", name: "Namibia", aliases: ["Republic of Namibia"] },
  { id: "ZAF", name: "South Africa", aliases: ["Republic of South Africa", "RSA"] },
  { id: "NLD", name: "Netherlands", aliases: ["Holland", "Kingdom of the Netherlands", "The Netherlands"] },
  { id: "OMN", name: "Oman", aliases: ["Sultanate of Oman"] },
  { id: "UZB", name: "Uzbekistan", aliases: ["Republic of Uzbekistan"] },
  { id: "KAZ", name: "Kazakhstan", aliases: ["Republic of Kazakhstan"] },
  { id: "TJK", name: "Tajikistan", aliases: ["Republic of Tajikistan"] },
  { id: "LTU", name: "Lithuania", aliases: ["Republic of Lithuania"] },
  { id: "BRA", name: "Brazil", aliases: ["Federative Republic of Brazil"] },
  { id: "URY", name: "Uruguay", aliases: ["Oriental Republic of Uruguay"] },
  { id: "MNG", name: "Mongolia", aliases: [] },
  { id: "RUS", name: "Russia", aliases: ["Russian Federation"] },
  { id: "CZE", name: "Czechia", aliases: ["Czech Republic", "Česko"] },
  { id: "DEU", name: "Germany", aliases: ["Federal Republic of Germany"] },
  { id: "EST", name: "Estonia", aliases: ["Republic of Estonia"] },
  { id: "LVA", name: "Latvia", aliases: ["Republic of Latvia"] },
  { id: "NOR", name: "Norway", aliases: ["Kingdom of Norway"] },
  { id: "SWE", name: "Sweden", aliases: ["Kingdom of Sweden"] },
  { id: "FIN", name: "Finland", aliases: ["Republic of Finland"] },
  { id: "VNM", name: "Vietnam", aliases: ["Socialist Republic of Vietnam"] },
  { id: "KHM", name: "Cambodia", aliases: ["Kingdom of Cambodia"] },
  { id: "LUX", name: "Luxembourg", aliases: ["Grand Duchy of Luxembourg"] },
  { id: "ARE", name: "United Arab Emirates", aliases: ["UAE"] },
  { id: "BEL", name: "Belgium", aliases: ["Kingdom of Belgium"] },
  { id: "GEO", name: "Georgia", aliases: [] },
  { id: "MKD", name: "North Macedonia", aliases: ["FYROM", "Macedonia", "Republic of North Macedonia"] },
  { id: "ALB", name: "Albania", aliases: ["Republic of Albania"] },
  { id: "AZE", name: "Azerbaijan", aliases: ["Republic of Azerbaijan"] },
  { id: "KOS", name: "Kosovo", aliases: ["Republic of Kosovo"] },
  { id: "TUR", name: "Turkey", aliases: ["Republic of Turkey", "Turkiye", "Türkiye"] },
  { id: "ESP", name: "Spain", aliases: ["Kingdom of Spain"] },
  { id: "LAO", name: "Laos", aliases: ["Lao PDR", "Lao People's Democratic Republic"] },
  { id: "KGZ", name: "Kyrgyzstan", aliases: ["Kyrgyz Republic"] },
  { id: "ARM", name: "Armenia", aliases: ["Republic of Armenia"] },
  { id: "DNK", name: "Denmark", aliases: ["Kingdom of Denmark"] },
  { id: "LBY", name: "Libya", aliases: [] },
  { id: "TUN", name: "Tunisia", aliases: ["Republic of Tunisia"] },
  { id: "ROU", name: "Romania", aliases: [] },
  { id: "HUN", name: "Hungary", aliases: ["Republic of Hungary"] },
  { id: "SVK", name: "Slovakia", aliases: ["Slovak Republic"] },
  { id: "POL", name: "Poland", aliases: ["Republic of Poland"] },
  { id: "IRL", name: "Ireland", aliases: [] },
  { id: "GRC", name: "Greece", aliases: ["Hellenic Republic"] },
  { id: "ZMB", name: "Zambia", aliases: ["Republic of Zambia"] },
  { id: "SLE", name: "Sierra Leone", aliases: ["Republic of Sierra Leone"] },
  { id: "GIN", name: "Guinea", aliases: ["Republic of Guinea"] },
  { id: "LBR", name: "Liberia", aliases: ["Republic of Liberia"] },
  { id: "CAF", name: "Central African Republic", aliases: ["CAR"] },
  { id: "SDN", name: "Sudan", aliases: ["Republic of the Sudan"] },
  { id: "DJI", name: "Djibouti", aliases: ["Republic of Djibouti"] },
  { id: "ERI", name: "Eritrea", aliases: ["State of Eritrea"] },
  { id: "AUT", name: "Austria", aliases: ["Republic of Austria"] },
  { id: "IRQ", name: "Iraq", aliases: ["Republic of Iraq"] },
  { id: "ITA", name: "Italy", aliases: ["Italian Republic"] },
  { id: "CHE", name: "Switzerland", aliases: ["Swiss Confederation"] },
  { id: "IRN", name: "Iran", aliases: ["Islamic Republic of Iran"] },
  { id: "LIE", name: "Liechtenstein", aliases: ["Principality of Liechtenstein"] },
  { id: "CIV", name: "Ivory Coast", aliases: ["Cote d'Ivoire", "Cote dIvoire", "Côte d'Ivoire", "Republic of Ivory Coast"] },
  { id: "SRB", name: "Serbia", aliases: ["Republic of Serbia"] },
  { id: "MLI", name: "Mali", aliases: ["Republic of Mali"] },
  { id: "SEN", name: "Senegal", aliases: ["Republic of Senegal"] },
  { id: "NGA", name: "Nigeria", aliases: ["Federal Republic of Nigeria"] },
  { id: "BEN", name: "Benin", aliases: ["Republic of Benin"] },
  { id: "AGO", name: "Angola", aliases: ["People's Republic of Angola"] },
  { id: "HRV", name: "Croatia", aliases: ["Republic of Croatia"] },
  { id: "SVN", name: "Slovenia", aliases: ["Republic of Slovenia"] },
  { id: "QAT", name: "Qatar", aliases: ["State of Qatar"] },
  { id: "SAU", name: "Saudi Arabia", aliases: ["Kingdom of Saudi Arabia", "KSA"] },
  { id: "BWA", name: "Botswana", aliases: ["Republic of Botswana"] },
  { id: "ZWE", name: "Zimbabwe", aliases: ["Republic of Zimbabwe"] },
  { id: "PAK", name: "Pakistan", aliases: ["Islamic Republic of Pakistan"] },
  { id: "BGR", name: "Bulgaria", aliases: ["Republic of Bulgaria"] },
  { id: "THA", name: "Thailand", aliases: ["Kingdom of Thailand"] },
  { id: "HTI", name: "Haiti", aliases: ["Republic of Haiti"] },
  { id: "DOM", name: "Dominican Republic", aliases: ["Dominican Rep."] },
  { id: "TCD", name: "Chad", aliases: ["Republic of Chad"] },
  { id: "KWT", name: "Kuwait", aliases: ["State of Kuwait"] },
  { id: "SLV", name: "El Salvador", aliases: ["Republic of El Salvador"] },
  { id: "GTM", name: "Guatemala", aliases: ["Republic of Guatemala"] },
  { id: "TLS", name: "Timor-Leste", aliases: ["Democratic Republic of Timor-Leste", "East Timor", "Timor Leste"] },
  { id: "BRN", name: "Brunei", aliases: ["Brunei Darussalam", "Negara Brunei Darussalam"] },
  { id: "DZA", name: "Algeria", aliases: ["People's Democratic Republic of Algeria"] },
  { id: "MOZ", name: "Mozambique", aliases: ["Republic of Mozambique"] },
  { id: "SWZ", name: "Eswatini", aliases: ["eSwatini", "Kingdom of eSwatini", "Kingdom of Eswatini", "Swaziland"] },
  { id: "BDI", name: "Burundi", aliases: ["Republic of Burundi"] },
  { id: "RWA", name: "Rwanda", aliases: ["Republic of Rwanda"] },
  { id: "MMR", name: "Myanmar", aliases: ["Burma", "Republic of the Union of Myanmar"] },
  { id: "BGD", name: "Bangladesh", aliases: ["People's Republic of Bangladesh"] },
  { id: "AND", name: "Andorra", aliases: ["Principality of Andorra"] },
  { id: "AFG", name: "Afghanistan", aliases: ["Islamic State of Afghanistan"] },
  { id: "MNE", name: "Montenegro", aliases: [] },
  { id: "BIH", name: "Bosnia and Herzegovina", aliases: ["Bosnia", "Bosnia and Herz.", "Bosnia Herzegovina"] },
  { id: "UGA", name: "Uganda", aliases: ["Republic of Uganda"] },
  { id: "CUB", name: "Cuba", aliases: ["Republic of Cuba"] },
  { id: "HND", name: "Honduras", aliases: ["Republic of Honduras"] },
  { id: "ECU", name: "Ecuador", aliases: ["Republic of Ecuador"] },
  { id: "COL", name: "Colombia", aliases: ["Republic of Colombia"] },
  { id: "PRY", name: "Paraguay", aliases: ["Republic of Paraguay"] },
  { id: "PRT", name: "Portugal", aliases: ["Portuguese Republic"] },
  { id: "MDA", name: "Moldova", aliases: ["Moldavia", "Republic of Moldova"] },
  { id: "TKM", name: "Turkmenistan", aliases: [] },
  { id: "JOR", name: "Jordan", aliases: ["Hashemite Kingdom of Jordan"] },
  { id: "NPL", name: "Nepal", aliases: [] },
  { id: "LSO", name: "Lesotho", aliases: ["Kingdom of Lesotho"] },
  { id: "CMR", name: "Cameroon", aliases: ["Republic of Cameroon"] },
  { id: "GAB", name: "Gabon", aliases: ["Gabonese Republic"] },
  { id: "NER", name: "Niger", aliases: ["Republic of Niger"] },
  { id: "BFA", name: "Burkina Faso", aliases: [] },
  { id: "TGO", name: "Togo", aliases: ["Togolese Republic"] },
  { id: "GHA", name: "Ghana", aliases: ["Republic of Ghana"] },
  { id: "GNB", name: "Guinea-Bissau", aliases: ["Republic of Guinea-Bissau"] },
  { id: "USA", name: "United States", aliases: ["America", "United States of America", "US", "USA"] },
  { id: "CAN", name: "Canada", aliases: [] },
  { id: "MEX", name: "Mexico", aliases: ["United Mexican States"] },
  { id: "BLZ", name: "Belize", aliases: [] },
  { id: "PAN", name: "Panama", aliases: ["Republic of Panama"] },
  { id: "VEN", name: "Venezuela", aliases: ["Bolivarian Republic of Venezuela"] },
  { id: "PNG", name: "Papua New Guinea", aliases: ["Independent State of Papua New Guinea", "PNG"] },
  { id: "EGY", name: "Egypt", aliases: ["Arab Republic of Egypt"] },
  { id: "YEM", name: "Yemen", aliases: ["Republic of Yemen"] },
  { id: "MRT", name: "Mauritania", aliases: ["Islamic Republic of Mauritania"] },
  { id: "GNQ", name: "Equatorial Guinea", aliases: ["Eq. Guinea", "Republic of Equatorial Guinea"] },
  { id: "GMB", name: "Gambia", aliases: ["Republic of the Gambia", "The Gambia"] },
  { id: "AUS", name: "Australia", aliases: ["Commonwealth of Australia"] },
  { id: "FJI", name: "Fiji", aliases: ["Republic of Fiji"] },
  { id: "NZL", name: "New Zealand", aliases: [] },
  { id: "MDG", name: "Madagascar", aliases: ["Republic of Madagascar"] },
  { id: "PHL", name: "Philippines", aliases: ["Republic of the Philippines"] },
  { id: "LKA", name: "Sri Lanka", aliases: ["Democratic Socialist Republic of Sri Lanka"] },
  { id: "BHS", name: "Bahamas", aliases: ["Commonwealth of the Bahamas", "The Bahamas"] },
  { id: "TWN", name: "Taiwan", aliases: ["Republic of China", "ROC"] },
  { id: "JPN", name: "Japan", aliases: [] },
  { id: "ISL", name: "Iceland", aliases: ["Republic of Iceland"] },
  { id: "KIR", name: "Kiribati", aliases: ["Republic of Kiribati"] },
  { id: "TTO", name: "Trinidad and Tobago", aliases: ["Republic of Trinidad and Tobago"] },
  { id: "GRD", name: "Grenada", aliases: [] },
  { id: "VCT", name: "Saint Vincent and the Grenadines", aliases: ["Saint Vincent", "St Vincent", "St Vincent and the Grenadines", "St. Vincent and the Grenadines"] },
  { id: "BRB", name: "Barbados", aliases: [] },
  { id: "LCA", name: "Saint Lucia", aliases: ["St Lucia", "St. Lucia"] },
  { id: "DMA", name: "Dominica", aliases: ["Commonwealth of Dominica", "D'inca"] },
  { id: "ATG", name: "Antigua and Barbuda", aliases: ["Antigua"] },
  { id: "KNA", name: "Saint Kitts and Nevis", aliases: ["Federation of Saint Kitts and Nevis", "Saint Kitts", "St Kitts", "St Kitts and Nevis", "St. Kitts and Nevis"] },
  { id: "JAM", name: "Jamaica", aliases: [] },
  { id: "MUS", name: "Mauritius", aliases: ["Republic of Mauritius"] },
  { id: "COM", name: "Comoros", aliases: ["Union of the Comoros"] },
  { id: "STP", name: "São Tomé and Principe", aliases: ["Democratic Republic of São Tomé and Principe", "São Tomé and Príncipe"] },
  { id: "CPV", name: "Cabo Verde", aliases: ["Cape Verde", "Republic of Cabo Verde"] },
  { id: "MLT", name: "Malta", aliases: ["Republic of Malta"] },
  { id: "SGP", name: "Singapore", aliases: ["Republic of Singapore"] },
  { id: "TON", name: "Tonga", aliases: ["Kingdom of Tonga", "Tongo"] },
  { id: "WSM", name: "Samoa", aliases: ["Independent State of Samoa"] },
  { id: "SLB", name: "Solomon Islands", aliases: [] },
  { id: "FSM", name: "Micronesia", aliases: ["Federated States of Micronesia", "FSM"] },
  { id: "VUT", name: "Vanuatu", aliases: ["Republic of Vanuatu"] },
  { id: "PLW", name: "Palau", aliases: ["Republic of Palau"] },
  { id: "BHR", name: "Bahrain", aliases: ["Kingdom of Bahrain"] },
  { id: "SMR", name: "San Marino", aliases: ["Republic of San Marino"] },
  { id: "MCO", name: "Monaco", aliases: ["Principality of Monaco"] },
  { id: "VAT", name: "Vatican City", aliases: ["Holy See", "State of the Vatican City", "Vatican"] },
  { id: "SYC", name: "Seychelles", aliases: ["Republic of Seychelles"] },
  { id: "MHL", name: "Marshall Islands", aliases: ["Republic of the Marshall Islands", "RMI"] },
  { id: "TUV", name: "Tuvalu", aliases: [] },
  { id: "MDV", name: "Maldives", aliases: ["Republic of Maldives"] },
  { id: "NRU", name: "Nauru", aliases: ["Republic of Nauru"] },
];
