import type { Pack, Place } from "./types";

const NORTHERN = "Northern";
const WESTERN = "Western";
const SOUTHERN = "Southern";
const EASTERN = "Eastern";

const places: Place[] = [
  { id: "ALB", name: "Albania", group: SOUTHERN, aliases: [] },
  { id: "AND", name: "Andorra", group: SOUTHERN, aliases: [] },
  { id: "AUT", name: "Austria", group: WESTERN, aliases: [] },
  { id: "BLR", name: "Belarus", group: EASTERN, aliases: ["belorussia", "byelorussia"] },
  { id: "BEL", name: "Belgium", group: WESTERN, aliases: [] },
  { id: "BIH", name: "Bosnia and Herzegovina", group: SOUTHERN, aliases: ["bosnia", "bosnia herzegovina"] },
  { id: "BGR", name: "Bulgaria", group: EASTERN, aliases: [] },
  { id: "HRV", name: "Croatia", group: SOUTHERN, aliases: [] },
  { id: "CYP", name: "Cyprus", group: SOUTHERN, aliases: [] },
  { id: "CZE", name: "Czechia", group: EASTERN, aliases: ["czech republic", "czechia"] },
  { id: "DNK", name: "Denmark", group: NORTHERN, aliases: [] },
  { id: "EST", name: "Estonia", group: NORTHERN, aliases: [] },
  { id: "FIN", name: "Finland", group: NORTHERN, aliases: [] },
  { id: "FRA", name: "France", group: WESTERN, aliases: [] },
  { id: "DEU", name: "Germany", group: WESTERN, aliases: ["deutschland"] },
  { id: "GRC", name: "Greece", group: SOUTHERN, aliases: ["hellas"] },
  { id: "HUN", name: "Hungary", group: EASTERN, aliases: [] },
  { id: "ISL", name: "Iceland", group: NORTHERN, aliases: [] },
  { id: "IRL", name: "Ireland", group: NORTHERN, aliases: ["republic of ireland", "eire", "éire"] },
  { id: "ITA", name: "Italy", group: SOUTHERN, aliases: [] },
  { id: "KOS", name: "Kosovo", group: SOUTHERN, aliases: [] },
  { id: "LVA", name: "Latvia", group: NORTHERN, aliases: [] },
  { id: "LIE", name: "Liechtenstein", group: WESTERN, aliases: [] },
  { id: "LTU", name: "Lithuania", group: NORTHERN, aliases: [] },
  { id: "LUX", name: "Luxembourg", group: WESTERN, aliases: ["luxemburg"] },
  { id: "MLT", name: "Malta", group: SOUTHERN, aliases: [] },
  { id: "MDA", name: "Moldova", group: EASTERN, aliases: ["moldavia"] },
  { id: "MCO", name: "Monaco", group: WESTERN, aliases: [] },
  { id: "MNE", name: "Montenegro", group: SOUTHERN, aliases: [] },
  { id: "NLD", name: "Netherlands", group: WESTERN, aliases: ["holland", "the netherlands"] },
  { id: "MKD", name: "North Macedonia", group: SOUTHERN, aliases: ["macedonia", "fyrom"] },
  { id: "NOR", name: "Norway", group: NORTHERN, aliases: [] },
  { id: "POL", name: "Poland", group: EASTERN, aliases: [] },
  { id: "PRT", name: "Portugal", group: SOUTHERN, aliases: [] },
  { id: "ROU", name: "Romania", group: EASTERN, aliases: [] },
  { id: "RUS", name: "Russia", group: EASTERN, aliases: ["russian federation"] },
  { id: "SMR", name: "San Marino", group: SOUTHERN, aliases: [] },
  { id: "SRB", name: "Serbia", group: SOUTHERN, aliases: [] },
  { id: "SVK", name: "Slovakia", group: EASTERN, aliases: ["slovak republic"] },
  { id: "SVN", name: "Slovenia", group: SOUTHERN, aliases: [] },
  { id: "ESP", name: "Spain", group: SOUTHERN, aliases: ["espana", "españa"] },
  { id: "SWE", name: "Sweden", group: NORTHERN, aliases: [] },
  { id: "CHE", name: "Switzerland", group: WESTERN, aliases: ["swiss"] },
  { id: "UKR", name: "Ukraine", group: EASTERN, aliases: [] },
  { id: "GBR", name: "United Kingdom", group: NORTHERN, aliases: ["uk", "britain", "great britain", "united kingdom of great britain and northern ireland"] },
  { id: "VAT", name: "Vatican City", group: SOUTHERN, aliases: ["vatican", "holy see"] },
];

export const europePack: Pack = {
  id: "europe",
  title: "The Countries",
  eyebrow: "Europe · 46 countries",
  geojsonUrl: "/europe.geojson",
  featureIdProperty: "id",
  places,
  groupColors: {
    [NORTHERN]: "#1d5a8a",
    [WESTERN]: "#2f6b4f",
    [SOUTHERN]: "#c56a1a",
    [EASTERN]: "#b42318",
  },
  frame: [
    [-25, 34.5],
    [40, 34.5],
    [40, 71.5],
    [-25, 71.5],
  ],
  viewBox: [840, 640],
  compactLabels: [
    "Malta",
    "Monaco",
    "Andorra",
    "Kosovo",
    "Latvia",
    "Serbia",
    "Poland",
    "Greece",
    "Cyprus",
  ],
  stripPrefixes: ["republic of", "the", "kingdom of", "grand duchy of"],
  mapLabel: "Map of the countries of Europe",
  unitSingular: "country",
  unitPlural: "countries",
  placeholder: "Name a country…",
  credit: "46 European countries · boundaries from Natural Earth",
  helpIntro:
    "Name the 46 countries of Europe, including the microstates, Cyprus, and Kosovo. Turkey and the Caucasus are left for another map.",
  helpItems: [
    "Type a country and press enter. Correct names fill in on the map.",
    "Colours mark Northern, Western, Southern, and Eastern Europe.",
    "Czechia and Czech Republic both count. So do UK, Britain, Holland, and Vatican City.",
    "No list to pick from. If you know it, you can name it.",
  ],
  winTitle: "The forty-six",
};
